version: '3'
services:
  mongo:
    image: mongo:5.0.21-rc0-focal
    volumes:
      - ./mongodata/data:/data/db
      - ./mongodata/log:/data/log
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      RANDOM_SECRET_STRING: ${RANDOM_SECRET_STRING}


  mongo-express:
    restart: always
    ports:
      - 8081:8081
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: ${MONGODB_CONNECTION_STRING}
      ME_CONFIG_BASICAUTH_USERNAME: mapiweb
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_WEB_PASSWORD}
    depends_on:
      - mongo

  broker:
    image: hivemq/hivemq4
    ports:
      - 8080:8080
      - 1883:1883

  mapi:
    image: sanyamarya/beeta-mapi
    volumes:
      - ./mapi-logs:/home/node/app/log
    ports:
      - 3000:3001
    env_file:
      - .env
    depends_on:
      - mongo
      - broker

  beeta-web:
    image: sanyamarya/beeta-manager
    ports:
      - 4200:80
    depends_on:
      - mapi
    env_file:
      - .env